using System;

namespace EasyTalk.Nodes.Core
{
    /// <summary>
    /// An enumeration defining all dialogue node types.
    /// </summary>
    [Serializable]
    public enum NodeType
    {
        UNKNOWN, ENTRY, EXIT, CONVO, OPTION, STORY, LIST, CONDITION, TRIGGER, JUMPIN, JUMPOUT,
        LOGIC, BOOL_VALUE, OPTION_MOD, FLAG_CHECK, FLAG_SET, CHARACTER_LIST, FLAG_LIST,
        RANDOM, SEQUENCE, BOOL_LOGIC, NUMBER_COMPARE, MATH, STRING_COMPARE, BOOL_VARIABLE, FLOAT_VARIABLE,
        INT_VARIABLE, STRING_VARIABLE, GET_VARIABLE_VALUE, SET_VARIABLE_VALUE, BUILD_STRING,
        PATH_SELECT, VALUE_SELECT, CONDITIONAL_VALUE, WAIT, PAUSE, PLAYER_INPUT, APPEND, AI_INIT, AI_ADD_MESSAGE, AI_PROMPT,
        AI_CLEAR, AI_READ, SHOW, HIDE, GOTO
    }
}